### ISSUE TITLE
This library do not works for 3.0.0 ESP8266 Core or higher

### ISSUE THREAD

**Issue by DavidRuizBarajas** [mrdunk/esp8266_mdns#17]
I tried several own scripts and the example **"mdns_test"** provided in the repo, and I only managed to work on the **2.7.4** version of the ESP8266 CORE or lower (provided by board manager on Arduino IDE). 

ESP8266 Core versions tested with: 
3.0.2
3.0.1
3.0.0
2.7.4
2.7.3
2.7.2

I write this just in case this info is helpful for others.

**Comment by mrdunk** [comment]
Thanks for the report.
It's a long time since i played with any of this code (or an ESP) but i think it could be fixed by anyone with enough patience.
From memory, this library needs to be passed a copy of the raw incoming packet.

My suggestion a few years ago here: https://github.com/mrdunk/esp8266_mdns/issues/12 seems relevant.
If you can fix how this library is getting the raw packet with later versions of CORE, the rest should still work.

good luck!

**Comment by ajanhalt** [comment]
I think I found the problem. There must have been a change in the UDP implementation. The constructor calls UDP.beginMulticast before the wifi connection is established. The only fix would be to call a begin() function after the wifi connection is there. BTW - I used this code before 3.0 so I tested a simple pgm with a constructor call vs a begin call. The constructor doesn't work anymore.

I can do a pull request for the change to add begin() and there's also issue #16 @clebermarinho where I think he's right (I made the same change). Also can I add a getRemoteIP() call to get the remote IP for the received packet ? I'm going to publish a relay for home mdns that needs it.

**Comment by mrdunk** [comment]
hi,
feel free to submit pull requests.
for the constructor issue and #16, i've no time to dig out the required hardware test this myself. if the code looks sane, i'll approve it.

For the `getRemoteIP()` thing,
are you suggesting adding a function to parse the returned MDNS packet?
I'd put that in a separate pull request.
It's a long time since i thought about this code so not sure where that would fit best. If i remember correctly this library leaves this sort of thing to the end user...
So maybe add your suggestion as one of the examples in the `examples` folder?

[Edit]
i just saw your other issue that addresses the `getRemoteIP()` thing. #18 
let's discuss this there.

**Comment by mrdunk** [comment]
https://github.com/mrdunk/esp8266_mdns/pull/19 fixes this.
